-- Local development environments inject the password via scripts/setup-dev.sh.
-- Production environments require the admin password to be set manually or via an env var initialization script on first-run.
-- The default static password hash has been removed from this file.
